### ISSUE TITLE
Mod errors 

### ISSUE THREAD

**Issue by Alucard0Reborn** [SpacedOutChicken/Smoky-Skies-Redux#10]
Archer obsoletes at tech Construction, and therefore Machinery for its upgrade Crossbowman may not yet be researched!
Pikeman obsoletes at tech Gunpowder, and therefore Metallurgy for its upgrade Lancer may not yet be researched!
Frigate obsoletes at tech Steam Power, and therefore Eruptives for its upgrade Battleship may not yet be researched!

**Comment by SpacedOutChicken** [comment]
Sorry for not closing this sooner. It's fixed.
