### ISSUE TITLE
Mod not selectable from "new game" menu

### ISSUE THREAD

**Issue by Zoogzin** [SpacedOutChicken/Smoky-Skies-Redux#2]
Lot of errors popup when i select this from the dropdown, but the real issue is that the mod won't stay selected - it just switches back to the last viable mod. I think a recent unciv update broke a lot of mods, like deciv and alpha frontier, which only started working after mod patches. Thanks for the help.

**Comment by SpacedOutChicken** [comment]
It needs updating in several areas. We're working on it.

**Comment by SpacedOutChicken** [comment]
The mod is now available without any errors. If you run into any further trouble, just raise a new issue and I'll work on it.
